# Generated by Django 4.1.1 on 2022-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(default="09/20/2022"),
            preserve_default=False,
        ),
    ]
